### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by nikilrselvam** [Yorko/gender-unbiased_BERT-based_pronoun_resolution#1]
Hi,
The repository (and frozen model in particular) seems to be missing requirements.txt. Would it please be possible to update the repo with the same?

Thank you!

**Comment by Yorko** [comment]
Hi! Thanks, indeed, this was somehow overlooked, added in 67d8c6b3fce94bbeb75bbc644a3111b168e7c25b
